CREATE DATABASE "customer_database";

CREATE TABLE states (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE cities (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(40) NOT NULL UNIQUE,
"stateId" INTEGER REFERENCES states(id)
);


